### ISSUE TITLE
Gulp needs updating for linting to be successful

### ISSUE THREAD

**Issue by azaceta** [open-toolchain/cloud-native-toolchain-tutorial#59]
The pipeline fails at the "Run Unit Test" step due to an error in fs.js, this is probably due to the node version not being compatible with gulp 3.
To fix it (locally) I've:
- updated package.json to pull gulp 4
```
@71  -   "gulp": "^3.9.1",
@71  -   "gulp": "^4.0.0",
```
- updated gulpfile.js:
```
@33 - gulp.task('lint', ['lint-js','lint-css']);
@33 + gulp.task('lint', gulp.parallel('lint-js','lint-css'));
@69 - gulp.task('dev-unit', ['dev-karma','dev-mocha']);
@69 + gulp.task('dev-unit', gulp.parallel('dev-karma','dev-mocha'));
```

Not sure how to contribute it to the project.

**Comment by padraic-edwards** [comment]
Thanks @azaceta - will take a look and fix.

**Comment by finbarro** [comment]
I have modified the files as suggested above by @azaceta , but I now get a different error..
`Pulling pipeline base image latest ...
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/pipeline/de3f0f2a-48ad-4fa9-add9-d7b65a0031a7/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/pipeline/de3f0f2a-48ad-4fa9-add9-d7b65a0031a7/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/pipeline/de3f0f2a-48ad-4fa9-add9-d7b65a0031a7/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)

Finished: FAILED`

**Comment by azaceta** [comment]
@finbarro that was the error for me before update gulp in the packages.json. Have you updated that one to ^4.0.0?

**Comment by finbarro** [comment]
Hi Asier, 
No, that was the error I got after I made the changes you suggested package.json and gulpfile.js in your OP. The error I got originally was pretty vague and unhelpful. 
`Preparing to start the job...
Pipeline image: latest
Preparing the build artifacts...
Pulling pipeline base image latest ...
Finished: FAILED` 
So, that is when I contacted once of the course creators who shared the link to your OP with me.... seems strange that I now get the error which your fix originally resolved!
Cheers, Fin.

**Comment by ludovic-gasc** [comment]
Hi,

This pull request should fix this issue: https://github.com/open-toolchain/cloud-native-toolchain-tutorial-app/pull/4

Regards

**Comment by ludovic-gasc** [comment]
The merge request has been merged: https://github.com/open-toolchain/cloud-native-toolchain-tutorial-app/pull/4

For me, this issue can be now closed, all problems in this issue has been addressed.
